# Generated by Django 3.2.11 on 2022-01-26 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='badania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataBadania', models.DateField()),
                ('typBadania', models.CharField(choices=[('MK', 'Morfologia krwi'), ('PW', 'Próby wątrobowe')], default='MK', max_length=2)),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.pacjentprofil')),
            ],
        ),
        migrations.CreateModel(
            name='morfologiaKrwi',
            fields=[
                ('badanie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='badania.badania')),
                ('HGB', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('HCT', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('WBC', models.DecimalField(blank=True, decimal_places=0, max_digits=5)),
                ('RBC', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('PLT', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('CRP', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='probyWatrobowe',
            fields=[
                ('badanie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='badania.badania')),
                ('ALT', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('AST', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('ALP', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('BIL', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('GGTP', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
            ],
        ),
    ]
